.mainnet.json, .testnet.json
- Update `.mainnet.json` and `.testnet.json` for ALPACA-BNB LPv1 -> ALPACA-BNB LPv2 migration.
Because PCSv2
=> deploy: finished queued timelock to add ALPACA-BNB LPv2 & disabled ALPACA-BNB LPv1 on FL

test/PancakeswapV2_StrategyAddBaseTokenOnly.test.ts
Commented out the case that not valid yet.
Because it made test failed.
=> chore: commented out revert when wrong token inject

contracts/6/token/GrazingRange.sol, test/GrazingRange.test.ts
This is an improvement PR for improving a reward distribution logic
Previously, all rewards will be calculated corresponding to the first deposit's block number rather than the actual campaign's starting block. This might create some leftover rewards in the grazing range contract if the first depositor deposits to the contract after the starting campaign.
So that all rewards will be distributed (no rewards are left in the contract)
=> [IMPROVEMENT] [GRAZING-RANGE] change reward distribution logic

contracts/6/token/GrazingRange.sol, test/GrazingRange.test.ts
This is a bugfix pr for fixing add reward info validation as well as adding the new validation
- for replacing currentEndBlock with rewardInfo[rewardInfo.length -1].endBlock, if the pushed rewardInfo's endblocks are [1,2,3,4,5] and current blocknumber is 3 and newly added endblock is 4, the validation will be passed. By changing the validation to  rewardInfo[rewardInfo.length -1].endBlock, if newly added endblock is 4, the function will be reverted since the latest end block is 5 and 5 > 4
- replace current End Block with the last end block as an end block validation
- add reward period validation, if the last reward period has ended, can't add more
=> [FIX] Add Reward Info validation

contracts/6.12/GrazingRange.sol, deploy/s018_timelock_add_rewardInfos_to_grazing_range.ts, hardhat.config.6.12.ts, package.json, test/GrazingRange.test.ts
This is a patch PR for fixing some grazing range's findings 
Some improvement, bugfixes are needed in order to let the user/owner seamlessly interact with the contract.
- upgrade solidity version from 0.6.6 to 0.6.12
- fix `_rewardBlockOf` method, when the current timeblock exceed the end timeblock, return 0
- adding more logic in `addRewardInfo` and `emergencyRewardWithdraw `in order to be able to validate when multiple campaigns share the same `rewardToken`, by adding the field called `totalRewards`, when `addRewardInfo`, `totalRewards` will be accumulated, based on `range * rewardPerBlock`, once the owner call emergency reward withdraw, replacing campaign.rewardToken.balanceOf(address(this)) with  campaign.totalRewards can solve this issue
- add more event called SetRewardInfoLimit, …
=> [FIX] Grazing Range findings

contracts/6.12/GrazingRange.sol, deploy/021_deploy_grazingRange.ts, deploy/s018_timelock_add_rewardInfos_to_grazing_range.ts, test/GrazingRange.test.ts
This is a refactor PR for removing a source of fund parameter and change to reward holder, only a single reward holder is allowed in the contract
because when the source of fund is a parameter for add reward info, if the owner is a malicious one, they might be able to use any account having approved a grazing range contract to bring a reward token to the contract. Changing to initialize parameter can fix this properly.
=> [REFACTOR] Remove source of fund and change to reward holder

contracts/6.12/GrazingRange.sol
So that transfer amount will be a previous amount rather than updated user's amount which is 0
=> [FIX] Create temp amount so that transfer will be transfered based on that amount rather than 0

contracts/6/protocol/Vault.sol, contracts/6/protocol/workers/CakeMaxiWorkerConfig.sol
This is a fixing PR based on the audit's suggestion
- move division part to the other side, thus making it a multiplication rather than division (try to avoid division)
try to avoid division to mitigate possible precision loss
=> [FIX] Improve Precision by multiplication and division reordering

contracts/6/protocol/workers/CakeMaxiWorker.sol
For tracking amount that is broughtback to beneficial vault during `reinvest()`
=> [FEAT] [CAKEMAXI] Add event for buyback beneficial vault token

contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseLiquidate.sol, test/PancakeswapV2_Restricted_SingleAsset_StrategyPartialCloseLiquidate.test.ts
Rename event in Single Asset Partial Close Liquidate.
Match with other strategies convention.
=> [main][chore] Rename event in Single Asset Partial Close Liquidate

contracts/6/protocol/workers/pcs/PancakeswapV2Worker02.sol, contracts/6/protocol/workers/single-asset/CakeMaxiWorker02.sol, contracts/6/protocol/workers/waultswap/WaultSwapWorker02.sol, test/CakeMaxiWorker02.test.ts, test/Vault_PancakeswapV202.test.ts, test/Vault_WaultSwap02.test.ts
Change reinvest threshold logic to make `reinvest()` always reinvest regardless of the `pendingXXX()`.
To avoid indefinitely pending rewards that won't get reinvested.
=> [main][feat] Update reinvest threshold logic

contracts/6/protocol/strategies/pancakeswap/StrategyAddBaseTokenOnly.sol, contracts/6/protocol/strategies/pancakeswap/StrategyAddTwoSidesOptimal.sol, contracts/6/protocol/strategies/pancakeswap/StrategyLiquidate.sol, contracts/6/protocol/strategies/pancakeswap/StrategyPartialCloseLiquidate.sol, contracts/6/protocol/strategies/pancakeswap/StrategyWithdrawMinimizeTrading.sol, contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseLiquidate.sol, contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseWithdrawMinimizeTrading.sol, contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyAddBaseTokenOnly.sol, contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyAddTwosidesOptimal.sol, contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyLiquidate.sol, contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyPartialCloseLiquidate.sol, contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyPartialCloseMinimizeTrading.sol, contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyWithdrawMinimizeTrading.sol, contracts/6/protocol/strategies/pancakeswapV2/PancakeswapV2StrategyAddBaseTokenOnly.sol, contracts/6/protocol/strategies/pancakeswapV2/PancakeswapV2StrategyAddTwoSidesOptimal.sol, contracts/6/protocol/strategies/pancakeswapV2/PancakeswapV2StrategyAddTwoSidesOptimalMigrate.sol, contracts/6/protocol/strategies/pancakeswapV2/PancakeswapV2StrategyLiquidate.sol, contracts/6/protocol/strategies/pancakeswapV2/PancakeswapV2StrategyPartialCloseLiquidate.sol, contracts/6/protocol/strategies/pancakeswapV2/PancakeswapV2StrategyWithdrawMinimizeTrading.sol, contracts/6/protocol/strategies/waultswap-restricted/WaultSwapRestrictedStrategyAddBaseTokenOnly.sol, contracts/6/protocol/strategies/waultswap-restricted/WaultSwapRestrictedStrategyAddTwoSidesOptimal.sol, contracts/6/protocol/strategies/waultswap-restricted/WaultSwapRestrictedStrategyLiquidate.sol, contracts/6/protocol/strategies/waultswap-restricted/WaultSwapRestrictedStrategyPartialCloseLiquidate.sol, contracts/6/protocol/strategies/waultswap-restricted/WaultSwapRestrictedStrategyPartialCloseMinimizeTrading.sol, contracts/6/protocol/strategies/waultswap-restricted/WaultSwapRestrictedStrategyWithdrawMinimizeTrading.sol
Resolved issues raised by the auditor during Partial Close strategies audit.
Make contracts even more secured.
- Using `safeTransfer` instead of `transfer` when working with `lpToken` in Partial Close contracts
- Reduced scope variables by re-order variables declaration.
- Better way to handling slippage in `Partial Close Single Asset Liquidate`
=> [main][chore] Resolved partial close strategies issues raised by audit

contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseLiquidate.sol, contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyPartialCloseLiquidate.sol, contracts/6/protocol/strategies/waultswap-restricted/WaultSwapRestrictedStrategyPartialCloseLiquidate.sol
Improve slippage handling on partial close liquidate for PCSv2 and WSwap
Make it more robust.
- PancakeswapV2RestrictedStrategyPartialCloseLiquidate.sol
- WaultSwapRestrictedStrategyPartialCloseLiquidate.sol
=> [main][chore] Improve slippage handling on partial close liquidate for PCSv2 and WSwap

contracts/6/protocol/Vault.sol, contracts/6/protocol/workers/WorkerConfig.sol, test/Vault_PancakeswapV202.test.ts, test/Vault_WaultSwap02.test.ts
- Improve `addCollateral` by adding killFactor sanity check when collateral is being added into the position. 
- Improve precision handling when check `maxPriceDiff`
This will prevent the edge case where users do `addCollateral` when position is under water but the collateral that is being added not enough to bring the position back to life. If such a case happened, the position will get liquidated even if collateral is being added and users will get charge from liquidate fees.
- Vault.sol
- tests
=> [main][improve] Add killFactor sanity check when `addCollateral`

test/integrations/protocol/delta-neutral/DeltaNeutralVaultConfig.test.ts
Delta Neutral Vault Config test.
- setSwapRouter on both positive and negative path
- setReinvestPath on both positive and negative path
=> [feat][feat] setSwapRouter, reInvestPath testcases

contracts/8.10/protocol/DeltaNeutralOracle.sol, scripts/fork/DeltaNeutralOracle.test.ts, test/integrations/protocol/DeltaNeutralOracle.test.ts
remove error when send no lpAmount.
- to prevent when initialize and worker get LP and always revert.
=> [feat][feat]: remove error when send no lpAmount

contracts/8.10/protocol/DeltaNeutralOracle.sol, contracts/8.10/protocol/DeltaNeutralVault.sol, contracts/8.10/protocol/interfaces/IERC20.sol, contracts/8.10/protocol/workers/DeltaNeutralMdexWorker02.sol, contracts/8.10/protocol/workers/DeltaNeutralPancakeWorker02.sol, contracts/8.10/utils/Math.sol, package.json, test/integrations/protocol/DeltaNeutralOracle.test.ts, test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts, test/integrations/protocol/delta-neutral/DeltaNeutralVaultNon18Decimals.test.ts, test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralMdexWorker02.test.ts, test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralPancakeWorker02.test.ts
- pad stable and asset tokens to 18 decimals before comparing value
- delta neutral oracle have to return Lp price in 18 decimals format
- support non 18 decimals token
=> [feat][feat] deltaneutral non18 decimal

contracts/8.10/protocol/DeltaNeutralVault.sol, hardhat.config.ts, test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts
Change how share was calculated during mining in Delta Neutral Vault's deposit.
Current calculation could lead to equity slowly bleed overtime
=> [main][feat] Change share calculation on Delta Neutral deposit

contracts/8.10/protocol/DeltaNeutralVault.sol, contracts/8.10/protocol/DeltaNeutralVaultConfig.sol, contracts/8.10/protocol/interfaces/IDeltaNeutralVaultConfig.sol, deploy/exec/delta-neutral-vault-config/deploy/delta-neutral-vault-config.ts, test/helpers/deploy.ts, test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts, test/integrations/protocol/delta-neutral/DeltaNeutralVaultConfig.test.ts
Change how withdraw health check compare actual loss against expected loss
Fix edge case that withdrawer can manipulate the debt ratio
- Use withdrawShareValue instead of withdrawValue
- Check changes in debt ratio in each vault instead of total debt ratio changes
- Adjust tolerance on debt ratio check from toloranceBps to 30 BPS (hardcoded)
=> [main][fix] Change withdraw logic check

contracts/8.10/protocol/DeltaNeutralVault.sol, test/integrations/protocol/delta-neutral/DeltaNeutralVaultNon18Decimals.test.ts
New calculation on withdraw value. Instead of using tokens return and assess the value. Use LP's value used in withdrawal - debt repaid.
Old calculation lead to larger equity loss due to Worker's LP amount as an multiplier to position value changes
ALPACA-3574
=> [main][fix] Use LP value - debt repaid in withdraw value calculation

contracts/8.10/protocol/RevenueTreasury.sol, contracts/8.10/protocol/interfaces/ISwapRouter.sol, contracts/8.10/protocol/mocks/MockSwapRouter.sol, test/integrations/protocol/RevenueTreasury.test.ts
Add more flexibility and reusability for Revenue Treasury
Previous version of the contract would need to be redeployed as
- There is not swap to transfer to vault
- There is no setter to update token, vault, remaining
- add setters
- add swap functionality before transfer to vault
=> [main][feat] Revenue Treasury enhancement

contracts/6/protocol/VaultAip42.sol, contracts/6/protocol/workers/waultswap/WaultSwapWorker02.sol, contracts/8.11/protocol/strategies/waultswap/StrategyOracleLiquidate.sol, deploy/exec/vault/upgrade/vault.ts, package.json, test/helpers/deploy.ts, test/integrations/protocol/workers/waultswap/VaultAip42_WaultSwapWorker02.test.ts
Supporting AIP4.2 (https://snapshot.org/#/alpacafinance.eth/proposal/0xb4f4a29393b7918116766b1ba84781d677941934b705fb4c20f5047c69c55fd0) by creating a new routine called `forceClose` on a special vault implementation, VaultAip42.sol. The `forceClose` routine will allow the deployer to force close WaultSwap positions to eliminate the bad debt risks from remaining WaultSwap positions.
This PR also included a new version of WaultSwapWorker02 to disable liquidation on the WaultSwap positions as there could be a chance that one position get forced close and it shallow up the liquidity depth of the pool which would create a risk of bad debts.
To eliminate the bad debt risks from WaultSwap positions.
- Add `VaultAip42.sol`
- Edit `WaultSwapWorker02`
- Add tests to all changes above
=> [main][feat] Support AIP4.2

contracts/8.10/protocol/DeltaNeutralVaultGateway.sol, package.json, test/integrations/protocol/delta-neutral/DeltaNeutralVaultGatewayNon18Decimals.test.ts
format decimal same as token decimal on swap logic
Delta neutral gateway is not support non18 decimals on swap
- format decimal on swap
- add test file
https://100x.atlassian.net/browse/ALPACA-3923
=> [main][feat][ALPACA-3923] delta neutral gw non18 decimals

solidity/contracts/8.10/protocol/DeltaNeutralVault.sol, test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts
Bounty was only count the pending Alpaca. But when there’s interaction with vault, there will be alpaca harvested and stay in delta neutral vault contract. This amount was neglected during bounty calculation and lead to too little bounty
Correct bounty collection
- edit DeltaNeutralVault.sol
- fix test file
=> [main][fix] Wrong bounty calculation

package.json, solidity/contracts/8.13/interfaces/ICreditor.sol, solidity/contracts/8.13/interfaces/IxALPACA.sol, solidity/contracts/8.13/xALPACACreditor.sol, solidity/tests/base/BaseTest.sol, solidity/tests/interfaces/xALPACACreditorLike.sol, solidity/tests/protocol/private-automated-vault/xALPACACreditor.t.sol, solidity/tests/utils/MockContract.sol, solidity/tests/utils/mocking.sol
A contract that assess credit line (in usd) per xALPACA that user's holding
So that each xALPACA holders can access to private AVs with appropriate credit line
- xALPACA creditor
- test in Forge
- MockContract for testing
- mocking lib
ALPACA-4092
=> [main][feat]  Assess credit of xALPACA holders

solidity/contracts/8.10/protocol/DeltaNeutralOracle.sol, test/integrations/protocol/DeltaNeutralOracle.test.ts
implement setOracle function on DeltaNeutralOracle contract
upgrade contract for flexibility to set oracle
- add setOracle function on DeltaNeutralOracle contract
ALPACA-4147
=> [main][feat][ALPACA-4147] add setOracle on DeltaNeutralOracle

solidity/contracts/8.13/DeltaNeutralVaultConfig02.sol, solidity/contracts/8.13/interfaces/IDeltaNeutralVaultConfig02.sol
Add executor configs to the delta neutral config 02
To mitigate risk of multiple upgrade or deployment for upcoming change, delta neutral config can be deployed before hand. Note that this relate to https://github.com/alpaca-finance/bsc-alpaca-contract/pull/305 which was implemented in parallel of Limited Access AV feature.
- DeltaNeutralConfig02
- IDeltaNeutralConfig02
=> [main][feat]: Add executor change to delta neutral config 02

package.json
Exclude typechain/index.ts when publish package.
In short, to optimize package user performance.
Longer version, to avoid the package user to import from `typechain/index.ts`, but instead, "directly imports" from its source file. "Direct import" significantly improve build performance (ex. frontend code) as it would only include what's really needed into the build, comparing to "index import" which would import everything as it compile the whole index file.
alpaca-4333
=> [main][chore][alpaca-4333] exclude typechain/index.ts when publish package

solidity/contracts/8.10/protocol/DeltaNeutralVault03.sol
Change withdraw executor argument
- Withdraw executor must retrieve from DeltaNeutral instead
=> [main][fix] change withdraw executor argument

package.json
Just move abi-to-sol package to dev dep.
Its child dependencies conflict with Frontend code.
=> [main][chore] move abi-to-sol package to dev dep

solidity/contracts/8.13/DeltaNeutralVault02.sol, solidity/tests/protocol/private-automated-vault/DeltaNeutralVault02.t.sol
Credit calculation will be off by large if the current total share in the vault is small relative to the depositing value 
Used credit was assessed after execute function but before minting share. This result in current "deposited" share got inflated in value thus failing the deposit which's not supposed to happened
Move the logic to calculate used credit to the very end after mint was done.
=> [main][fix]: Fix incorrect credit tracking

solidity/contracts/8.13/AutomatedVaultController.sol, solidity/contracts/8.13/utils/LinkList.sol, solidity/tests/interfaces/AutomatedVaultControllerLike.sol, solidity/tests/protocol/private-automated-vault/AutomatedVaultController.t.sol
This PR introduced a circular linked list as the data structure to store the addresses of Private AV for easy and efficient usage at the `AutomatedVaultController`.
To optimize gas usage.
- Add `LinkList` library
- Use `LinkList` for `privateVaults` in `AutomatedVaultController`
=> [main] [feat] use LinkList to store privateVaults for efficient retrieval

solidity/contracts/8.13/nft-staking/NFTStaking.sol, solidity/tests/NFTStakingTest.t.sol
improve/fix contract function
Unstake nft, unlock time expire logic is go wrong
Stake nft, can revert if we try send unlocktime equal with current timestamp but block is mined.
- `stakeNFT` prevent send past timestamp
- `unstakeNFT` fix logic to check expired
- fix test
=> [main][fix] modify nft staking contract
