alpaca-finance/bsc-alpaca-contract

contracts/6/token/GrazingRange.sol
test/GrazingRange.test.ts

This is a fix PR for fixing some issues rewarding andit's findings
There are 5 fixes in this PR
- `pendingReward()'s lastRewardBlock cursor`
- `public` to `external ` in `initialized()`
- `emergencyWithdraw()` updated total staked
- `emergencyRewardWithdraw()` amount validation
- `nonreentrancy guard on emergencyWithdraw and emergencyRewardWithdraw`
- Some issues contain medium/crucial severity.

[FIX] Fix some Bugs on Grazing Range regarding audit's findings

---

contracts/6.12/GrazingRange.sol

This is a fixed PR based on slowmist's suggestions
To be more secured, obviously
- follow the check-effects-interaction for `emergencyWithdraw`

[FIX] Fix grazing range audit findings

---

.testnet.json
deploy/s017_timelock_add_campaigns_to_grazing_range.ts
deploy/s018_timelock_add_rewardInfos_to_grazing_range.ts

Add campaign on testnet for QA test.
Because QA.

deploy: finished add campaign on testnet

---

.mainnet.json
deploy/s017_timelock_add_campaigns_to_grazing_range.ts
deploy/s018_timelock_add_rewardInfos_to_grazing_range.ts

deploy: queued BOR on Grazing Range

---

.mainnet.json
.testnet.json
package.json
scripts/validate-config.ts
tsconfig.json

Update json format for both mainnet and testnet

chore: finished adjust json format

---

test/FairLaunch.test.ts
test/FairLaunchV2.test.ts

FairLaunch test code typo fixed
In order to provide correct information
test: FairLaunch typo fixed

test: FairLaunch test code typo fixed

---

contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyAddTwosidesOptimal.sol
contracts/6/protocol/strategies/waultswap-restricted/WaultSwapRestrictedStrategyAddTwoSidesOptimal.sol

- remove a few line of unused code

[Refactor] Remove redundant line of codes

---

deploy/016_deploy_pancakeswapV2_workers.ts
deploy/028_deploy_waultswap_workers.ts

- Improve Pancakeswap Worker deployment script
To make thing easier to deploy and consume less time.

feat: finished improve pcs worker deploy script

---

contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedCakeMaxiStrategyAddBaseWithFarm.sol
test/PancakeswapV2_Restricted_SingleAsset_StrategyAddBaseWithFarm.test.ts

This is a patch pr for adding a base token balance validation

[main][Patch] SingleAsset add base with farm strategy's balance validation

---

contracts/6/protocol/ConfigurableInterestVaultConfig.sol
contracts/6/protocol/SimpleVaultConfig.sol
contracts/6/protocol/Vault.sol
contracts/6/protocol/interfaces/IVaultConfig.sol
contracts/6/protocol/mock/MockContractContext.sol
test/Vault_PancakeswapV2.test.ts

Add ability to allow whitelisted non-EOA to interact with restricted functions.
For more composability

[main][feat] Enable whitelist caller

---

contracts/6/protocol/ConfigurableInterestVaultConfig.sol

Fix InterestModel event emit
Because need to cast it to address

[main][chore] chore: fix interestModel address cast

---

contracts/6/protocol/OracleMedianizer.sol
contracts/6/protocol/mock/MockAggregatorV3.sol
deploy/s025_add_primary_source_oracle_medianizer.ts
test/OracleMedianizer.test.ts

- oracle medianizer contract add max price stale
Because we are integrating Chainlink

[main][feat] add maxPriceStale to OracleMedianizer

---

.mainnet.json
.testnet.json
deploy/016_deploy_pancakeswapV2_workers.ts
deploy/028_deploy_waultswap_workers.ts
deploy/s013_testnet_deploy_tokens_and_liquidity.ts
deploy/s017_timelock_add_campaigns_to_grazing_range.ts
deploy/s018_timelock_add_rewardInfos_to_grazing_range.ts

Deploy MATIC-USDT and FORM-BUSD to mainnet
Add new pools.

[main][deploy] Deploy MATIC-USDT and FORM-BUSD

---

contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyPartialCloseMinimizeTrading.sol
deploy/022_deploy_pancake_v2_restricted_share_strategies.ts
package.json
test/PancakeswapV2_Restricted_StrategyPartialCloseMinimizeTrading.test.ts
test/Vault_PancakeswapV2.test.ts

- pancake swap V2 restricted strategy partial close minimize trading contract
- deployment script
users want to have an option to partially close their position, payback their debt, and minimize trading

[main][feat]pancakeswap v2 restricted strategy partial close minimize trading

---

contracts/6/protocol/strategies/waultswap-restricted/WaultSwapRestrictedStrategyPartialCloseMinimizeTrading.sol
deploy/029_deploy_waultswap_restricted_share_strategies.ts
package.json
test/Vault_WaultSwap.test.ts
test/WaultSwap_Restricted_StrategyPartialCloseMinimizeTrading.test.ts

- wault swap restricted strategy partial close minimize trading contract
- deployment script
users want to have an option to partially close their position, payback their debt, and minimize trading

[main][feat]wault swap restricted strategy partial close minimize trading

---

deploy/s029_timelock_set_reinvest_config_workers02.ts

Adding script to config reinvest parameters.
Config reinvest.

[main][feat] Add script to config reinvest parameters

---

.mainnet.json
.testnet.json
deploy/016_deploy_pancakeswapV2_workers.ts
deploy/s011_timelock_update_worker_workconfig_params.ts
deploy/s013_testnet_deploy_tokens_and_liquidity.ts

Add TRX-WBNB and BTT-WBNB pools to mainnet.
Because we launch them.

[main][deploy] Deploy TRX-WBNB and BTT-WBNB pools

---

contracts/6/protocol/OracleMedianizer.sol

-  change function visibility _getPrice
- OracleMedianizer.sol

[main][fix] change visibility function

---

contracts/6/protocol/interest-models/TripleSlopeModel.sol
test/TripleSlopeModel.test.ts

Adjust the interest model.
*Current model:*
0% - 50%:  Linear slope from 0% →  20%
50 - 90%:  Flat 20%
90 - 100%: Linear model from 20% → 150% 
*New model:*
0 - 60%: Linear slope from 0 → 20%
60% - 90%:  Flat 20%
90 - 100%: Linear model from 20% → 150% 
Optimized assets utilization and interest.

[main][feat] Adjust interest model

---

.mainnet.json
.openzeppelin/unknown-56.json
.openzeppelin/unknown-97.json
contracts/6/protocol/ConfigurableInterestVaultConfig.sol
contracts/6/protocol/Vault.sol
deploy/033_deploy_pancakeswapV2_worker02.ts
deploy/s007_upgrade_vault.ts
deploy/s010_timelock_set_param_vault_config.ts
deploy/s022_upgrade_vault_config.ts
deploy/s023_set_max_kill_bps.ts
deploy/s027_timelock_add_treasury_fields_workers_02.ts
package.json
test/CakeMaxiWorker02.test.ts
test/Vault_Pancakeswap.test.ts
test/Vault_PancakeswapV2.test.ts
test/Vault_PancakeswapV202.test.ts
test/Vault_WaultSwap.test.ts
test/Vault_WaultSwap02.test.ts
yarn.lock

Deployed ChainLink integration, Vault Config v1.0.2, and Vault v1.1.0
Launch it.

[main][deploy] Deploy ChainLink integration, TUSD Vault, TUSD pool, Vault Config v1.0.2, and Vault v1.1.0.

---

test/CakeMaxiWorker.test.ts
test/Vault_PancakeswapV2.test.ts
test/Vault_PancakeswapV202.test.ts
test/Vault_WaultSwap.test.ts
test/Vault_WaultSwap02.test.ts
test/helpers/deploy.ts

Update partial close liquidate integration tests and refactor tests.
To support new slippage handling

[main][chore] Update partial close liquidate integration tests

---

.mainnet.json
.testnet.json
deploy/interfaces/config.ts
scripts/validate-config.ts

feat : add deployedBlock mainnet and testnet json

[main][feat] Add deployedBlock to mainnet and testnet.json

---

test/Vault_PancakeswapV202.test.ts
test/helpers/fixtures/Vault_PancakeswapV202.ts

Implement fixture in test to make it run faster.
Previously it is slow to run e2e test. It takes like 10ish minutes to finish the test, after implement fixture the test finish in 4 minutes.

[main][refactor] Refactor Vault_PancakeswapV202 test to make it run faster

---

contracts/6/protocol/apis/mdex/BSCPool.sol
contracts/6/protocol/apis/mdex/EnumerableSet.sol
contracts/6/protocol/apis/mdex/IMasterChefBSC.sol
contracts/6/protocol/apis/mdex/IMdexFactory.sol
contracts/6/protocol/apis/mdex/IMdexPair.sol
contracts/6/protocol/apis/mdex/IMdexRouter.sol
contracts/6/protocol/apis/mdex/IMdx.sol
contracts/6/protocol/apis/mdex/IOracle.sol
contracts/6/protocol/apis/mdex/ISwapMining.sol
contracts/6/protocol/apis/mdex/MdexRouter.sol
contracts/6/protocol/apis/mdex/SwapMining.sol
contracts/6/protocol/apis/mdex/TransferHelper.sol
contracts/6/protocol/interfaces/IWBNB.sol

- add related Mdex contract to bsc-alpaca-contract
- for integration with mdex

[mdex-integration][feat][add-mdex-contracts] add related Mdex contracts

---

contracts/5/protocol/apis/mdex/MdexFactory.sol

- add MdexFactory contract
- for integration with Mdex

[mdex-integration][feat] add MdexFactory

---

package.json
yarn.lock

[main][chore] Upgrade dependency 

---

contracts/6/protocol/apis/mdex/MdxToken.sol

[mdex-integration][feat] add MdxToken Contract

---

contracts/6/protocol/workers/mdex/MdexWorker.sol
package.json
test/Vault_MdexWorker.test.ts
test/helpers/deploy.ts

[mdex-worker][feat] mdex worker modification

---

contracts/6.12/protocol/apis/scientix/Import.sol
package.json
yarn.lock

Import Scientix contracts to our project.
We are going to integrate with them in some way.

[main][chore] import Scientix contracts

---

contracts/6/protocol/mock/MockMdexWorker.sol
contracts/6/protocol/strategies/mdex/MdexRestrictedStrategyAddBaseTokenOnly.sol
contracts/6/protocol/strategies/mdexswap-restricted/MdexRestrictedStrategyAddBaseTokenOnly.sol
package.json
test/Mdex_Restricted_StrategyAddBaseTokenOnly.test.ts

[mdex-integration][feat] implement mdex add base token only strat.

---

contracts/6/protocol/mock/MockMdexWorker.sol
contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyAddTwosidesOptimal.sol
package.json
test/Mdex_Restricted_StrategyAddTwoSidesOptimal.test.ts

- add MdexRestrictedStrategyAddTwosidesOptimal Strategy

[mdex-integration][feat] add mdex twosidesoptimal strategy

---

contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyAddBaseTokenOnly.sol
contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyAddTwosidesOptimal.sol
contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyLiquidate.sol
contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyPartialCloseLiquidate.sol
contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyPartialCloseMinimizeTrading.sol
contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyWithdrawMinimizeTrading.sol
contracts/6/protocol/workers/mdex/MdexWorker02.sol

- fix getMiningRewards pass pool id instead of index

[main][fix] mdex-strategy-getMiningRewards

---

test/Vault_MdexWorker02.test.ts
test/helpers/deploy.ts

[main][hotfix] add missing parameter from strategy contract

---

contracts/6/protocol/workers/mdex/MdexWorker02.sol
test/Vault_MdexWorker02.test.ts

- Withdraw mdx reward only the amount that is transferred from swapMining
- Validate input reward path instead of state variable

[main][fix]: mdex worker improper withdraw reward and reward path

---

contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyAddBaseTokenOnly.sol
contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyAddTwosidesOptimal.sol
contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyLiquidate.sol
contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyPartialCloseLiquidate.sol
contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyPartialCloseMinimizeTrading.sol
contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyWithdrawMinimizeTrading.sol
contracts/6/protocol/workers/mdex/MdexWorker02.sol

Clean MDEX Worker & Strategies. Add events and better handling when withdrawTaker fees on strategies contract.
Make it cleaner.

[main][chore] Clean mdex worker & strategies

---

.mainnet.json
.openzeppelin/unknown-56.json
.openzeppelin/unknown-97.json
.testnet.json
deploy/exec/dex/deploy/token-liq-pool.ts
deploy/exec/grazing-ranges/config/add-campaign-info.ts
deploy/exec/grazing-ranges/config/add-reward-info.ts
deploy/exec/workers/deploy/pancakeswap-v2-workers02.ts

Deploy LEON Graze, BTCB-ETH and ETH-BTCB pools

[main][deploy] LEON Graze 

---

.mainnet.json
deploy/exec/grazing-ranges/config/add-campaign-info.ts
deploy/exec/grazing-ranges/config/add-reward-info.ts

[main][deploy] WNOW graze

---

.mainnet.json
deploy/exec/grazing-ranges/config/add-campaign-info.ts
deploy/exec/grazing-ranges/config/add-reward-info.ts
scripts/withdraw-reserve.ts

[main][deploy] Add TEN and DEP to Graze

---

.mainnet.json
deploy/exec/grazing-ranges/config/add-campaign-info.ts
deploy/exec/grazing-ranges/config/add-reward-info.ts

[main][deploy] CAPS Graze

---

.mainnet.json
.testnet.json

update mainnet testnet eternal

[main][chore][alpaca 2389] : update mainnet testnet eternal

---

.mainnet.json
deploy/exec/fairlaunch/config/add-pool.ts
deploy/exec/fairlaunch/config/set-pool.ts
deploy/exec/timelock/timelock-execution.ts
deploy/exec/vault-config/config/set-whitelisted-callers.ts
deploy/exec/workers/config/set-beneficial-vault-config.ts
deploy/exec/workers/config/set-reinvest-config.ts
deploy/exec/workers/config/set-treasury-config.ts
deploy/services/timelock.ts

[main][deploy] xALPACA to mainnet

---

package.json
test/GrazingRange.test.ts
test/Vault_MdexWorker02.test.ts
test/Vault_Pancakeswap.test.ts
test/Vault_PancakeswapV2.test.ts
test/Vault_PancakeswapV202.test.ts
test/Vault_Pancakeswap_Migrate.test.ts
test/Vault_WaultSwap.test.ts
test/Vault_WaultSwap02.test.ts
yarn.lock

Upgrade dependencies made some test cases failed. This PR fix that.
Because test shouldn't fail.

[main][chore] Update test cases after upgrade dependencies

---

deploy/exec/fairlaunch/config/set-alpaca-per-block.ts
deploy/exec/timelock/timelock-execution.ts
deploy/exec/vault-config/config/set-whitelisted-callers.ts
package.json

Add emission adjustment script.

[main][feat] Add emission adjustment script

---

contracts/8.10/protocol/DeltaNeutralVault.sol
contracts/8.10/protocol/DeltaNeutralVaultConfig.sol

refactor: alpaca distribution method and document

[feat][feat]: refactor: alpaca distribution method and document

---

contracts/8.10/protocol/DeltaNeutralVaultConfig.sol

[feat][refactor]: alpaca distribution

---

package.json
test/integrations/protocol/delta-neutral/DeltaNeutralVaultConfig.test.ts

- Implement unit test for delta neutral vault config

[test] create unit test delta neutral vault config

---

contracts/8.10/protocol/PriceHelper.sol
hardhat.config.8.10.forking.ts
package.json
scripts/fork/PriceHelper.test.ts

test mainnet fork of priceHelper delta neutral

[feat][test] : test mainnet fork of priceHelper delta neutral

---

contracts/6.12/protocol/apis/mars-ecosystem/ILiquidityMiningMaster.sol
package.json

[main][feat] support xms gr

---

test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts

[feat][feat] delta neutral vault deposit test case

---

contracts/8.10/protocol/DeltaNeutralVault.sol
contracts/8.10/utils/FixedPointMathLib.sol
test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts

- Re-order parameters for deposit and withdraw function
- use replace SafeToken by SafeERC20Upgradeable

[feat][feat] refactor delta neutral vault

---

contracts/8.10/protocol/workers/DeltaNeutralMdexWorker02.sol
contracts/8.10/protocol/workers/DeltaNeutralPancakeWorker02.sol

Claim farm reward instead of withdraw all LP
Save gas cost

[feat][feat]: change worker _reinvest() logic

---

contracts/8.10/protocol/DeltaNeutralVault.sol
contracts/8.10/protocol/DeltaNeutralVaultConfig.sol
contracts/8.10/protocol/interfaces/IDeltaNeutralVaultConfig.sol
test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts

Add functionality to provide different leverage level
Each Delta Neutral Vault can have different leverage level per risk appetite
a3fd25c618fbc5a2e15e8becfeb112a2127555f0 feat: add dynamic leverage level
- apply FixedMathLib library
- Add test coverage for different leverage level

[feat][feat]: add dynamic leverage level

---

contracts/8.10/protocol/DeltaNeutralVault.sol
contracts/8.10/protocol/DeltaNeutralVaultConfig.sol
contracts/8.10/protocol/interfaces/IDeltaNeutralVaultConfig.sol
test/helpers/deploy.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts

- deduct shares from user when they deposit as deposit fee
- to collect deposit fee

[feat][feat] delta neutral deposit fee

---

contracts/8.10/protocol/DeltaNeutralVault.sol
contracts/8.10/protocol/DeltaNeutralVaultConfig.sol
contracts/8.10/protocol/interfaces/IDeltaNeutralVaultConfig.sol
test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVaultConfig.test.ts

- require total position value after deposit to not exceed maximum position value which defined in delta vault config
- we want to limit the position size of delta neutral vault

[feat][feat] delta neutral deposit size limit

---

contracts/8.10/protocol/DeltaNeutralOracle.sol
contracts/8.10/protocol/DeltaNeutralVault.sol
contracts/8.10/protocol/interfaces/IDeltaNeutralOracle.sol
contracts/8.10/protocol/workers/DeltaNeutralMdexWorker02.sol
contracts/8.10/protocol/workers/DeltaNeutralPancakeWorker02.sol
test/helpers/deploy.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts
test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralMdexWorker02.test.ts
test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralPancakeWorker02.test.ts

- rename PriceHelper contract to DeltaNeutralOracle
- re-order withdraw function params
- using SafeERC20Upgradeable for IERC20Upgradeable

[feat][feat] delta neutral refactor

---

contracts/8.10/protocol/DeltaNeutralVault.sol
contracts/8.10/protocol/DeltaNeutralVaultConfig.sol
contracts/8.10/protocol/interfaces/IDeltaNeutralVaultConfig.sol
test/helpers/deploy.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVaultConfig.test.ts

[feat][feat] delta neutral reinvest

---

contracts/8.10/protocol/DeltaNeutralVault.sol
contracts/8.10/utils/FullMath.sol
contracts/8.10/utils/Math.sol

- use FullMath to prevent overflow
- remove internal claim

[feat][feat] delta neutral refactor 3

---

contracts/8.10/protocol/DeltaNeutralVault.sol
test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts

- refactor when set mock price for DeltaNeutralOracle
- add comments to unit test
- improve readability

[feat][feat] delta neutral refactor test

---

contracts/8.10/protocol/DeltaNeutralVault.sol

- change method of swapping token to "swapExactTokenForTokens"

[feat][fix] : change swap method on delta neutral vault

---

contracts/8.10/protocol/workers/DeltaNeutralMdexWorker02.sol
contracts/8.10/protocol/workers/DeltaNeutralPancakeWorker02.sol

refactor delta neutral workers

[feat][refactor] deltanet worker

---

test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts

- config vault interest rate to 0 for simple calculation
- add more comments and asserts for positive withdraw uint test

[feat][feat] add comments for withdraw unit test

---

contracts/6/protocol/apis/pancakeV2/PancakeRouterV2.sol
contracts/8.10/protocol/DeltaNeutralVault.sol
test/helpers/swap.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts

- add test for #reinvest method 
- for cover in both success and fail cases.

[feat][test]: test reinvest

---

contracts/8.10/protocol/DeltaNeutralVault.sol
hardhat.config.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts

- validate withdraw value to less than withdrawShareValue

[feat][feat] delta neutral withdraw check

---

contracts/8.10/protocol/DeltaNeutralVault.sol

- prevent precision loss in withdrawHealthCheck by cross multiplication

[feat][fix] withdrawHealthCheck precision loss

---

contracts/8.10/protocol/DeltaNeutralOracle.sol
contracts/8.10/protocol/DeltaNeutralVault.sol
contracts/8.10/protocol/DeltaNeutralVaultConfig.sol
contracts/8.10/protocol/DeltaNeutralVaultGateway.sol
contracts/8.10/protocol/workers/DeltaNeutralMdexWorker02.sol
contracts/8.10/protocol/workers/DeltaNeutralPancakeWorker02.sol
test/integrations/protocol/DeltaNeutralOracle.test.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVaultConfig.test.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVaultGateway.test.ts
test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralMdexWorker02.test.ts
test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralPancakeWorker02.test.ts

[feat][feat] delta neutral error naming

---

.fantom_mainnet.json
.fantom_testnet.json
.openzeppelin/unknown-250.json
.openzeppelin/unknown-4002.json
deploy/exec/oracles/config/add-primary-source-oracle-medianizer.ts
deploy/exec/strategies/deploy/spookyswap/vault-strategies.ts
deploy/exec/vault-config/deploy/vault-config.ts
deploy/exec/vault/deploy/minifl-vault.ts
deploy/exec/workers/deploy/spookyswap-workers03.ts

Deploy Alpaca Vault and ALPACA-WFTM pools to Fantom.

[main][deploy] Alpaca Vault, ALPACA-WFTM double-sided pools

---

contracts/8.10/protocol/DeltaNeutralVault.sol
test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts

[feat][feat] delta neutral fix issue

---

contracts/8.10/protocol/DeltaNeutralVault.sol
test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts

- require minimum token receive when swap reward token
- protect reinvest from sandwich attack

[feat][fix] delta neutral reinvest slippage

---

.fantom_mainnet.json
.fantom_testnet.json
.openzeppelin/unknown-250.json
.openzeppelin/unknown-4002.json
deploy/exec/dex/deploy/token-liq-pool.ts
deploy/exec/workers/deploy/spookyswap-workers03.ts
hardhat.config.5.ts
hardhat.config.6.12.ts
hardhat.config.8.11.ts
hardhat.config.ts

[main][deploy] Deploy Spooky BTC-WFTM, fUSDT-WFTM, DAI-WFTM, MIM-WFTM pools

---

contracts/8.10/protocol/DeltaNeutralVault.sol
contracts/8.10/protocol/DeltaNeutralVaultConfig.sol
test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts

- change maxVaultPositionValue to public modifier
- add setPriceOracle and setDeltaVaultConfig to DeltaNeutralVault
- DeltaNeutralVault.sol
- DeltaNeutralVaultConfig.sol

[feat][fix] delta neutral vault set config and oracle

---

contracts/vyper/2.11/apis/StableSwap.vy
contracts/vyper/2.11/apis/Token.vy
hardhat.config.vyper.2.11.ts
package.json
yarn.lock

Add StableSwap Typechain for FE integration. Note: you will need to delete `gas` key in factories of Vyper contracts then do `yarn build`
Because FE needs it.
- Add `hardhat.config.vyper.2.11.ts` to allow project to be able to compile Vyper
- Add EPS's StableSwap contract.

[main][chore] Add StableSwap Typechain

---

.solhint.json
contracts/8.10/protocol/DeltaNeutralVault.sol
contracts/8.10/protocol/DeltaNeutralVaultConfig.sol
contracts/8.10/protocol/interfaces/IDeltaNeutralVaultConfig.sol
deploy/exec/delta-neutral-worker/deploy/delta-neutral-pcs-worker.ts
package.json
test/helpers/deploy.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVault.test.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVaultConfig.test.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVaultGateway.test.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVaultNon18Decimals.test.ts

Separate treasury account for better accounting and also auto diverge ALPACA earned from FairLaunch to Beneficiary address. The beneficiary address is expected to be `AlpacaFeeder` where ALPACA there will be fed to xALPACA holders. 
- Better accounting

[main][feat] Separate treasury account for better accounting

---

contracts/8.10/token/EmissionForwarder.sol
contracts/8.10/token/ProxyToken.sol
contracts/8.10/token/interfaces/IAnyswapV4Router.sol
contracts/8.10/token/interfaces/IERC20.sol
contracts/8.10/token/interfaces/IFairLaunch.sol
contracts/8.10/token/interfaces/IProxyToken.sol
package.json
test/integrations/token/EmissionForwarder.test.ts

Renamed FairLaunchRelayer to EmissionForwarder and refactor ProxyToken.

[main][chore] FairLaunchRelayer -> EmissionForwarder & refactor

---

contracts/8.10/protocol/RevenueTreasury.sol
contracts/8.10/protocol/interfaces/IGrassHouse.sol
contracts/8.10/protocol/interfaces/ISwapRouter.sol
contracts/8.10/protocol/mocks/MockGrassHouse.sol
contracts/8.10/protocol/mocks/MockSwapRouter.sol
contracts/8.10/protocol/mocks/MockVault.sol
package.json
test/integrations/protocol/RevenueTreasury.test.ts

A new contract that receive a token and distribute to vault (bad debt insurance cover) and xALPACA holder (GrassHouse)
Fulfil AIP4.1 
https://snapshot.org/#/alpacafinance.eth/proposal/0xec36d90586f65a2bceef31be5625551e34d0d1ecb9dab8acd2c4333aefc8bc9c
- RevenueTreasury contract
- Mock Vault contract for testing
- Mock GrassHouse contract for testing
- Mock Swap Router contract for testing
- Unit test
ALPACA-3781

[main][feat] Revenue Treasury to handle split distribution

---

.mainnet.json
deploy/exec/delta-neutral-vault/config/init-positions.ts
deploy/exec/timelock/timelock-execution.ts
deploy/exec/triple-slope-model/deploy/triple-slope-model.ts
deploy/exec/vault-config/config/set-params.ts
deploy/exec/worker-config/config/set-configs.ts
deploy/services/timelock.ts
hardhat.config.ts
package.json

- Deploy a new N8X-PCS2 DeltaNeutral Vault
- Deploy a new TripleSlope model for ibUSDT and ibWBNB
- Keep up with the demands for the delta neutral products

[main][deploy] Deploy a new N8X-PCS2 & TripleSlope to BSC mainnet

---

package.json
test/integrations/protocol/delta-neutral/DeltaNeutralVaultGateway.test.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVaultGatewayWithSpookyRouter.test.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVaultGatewayWithSpookySwap.test.ts

Add test case for DeltaVaultGateway with SpookySwap and MiniFairLaunch on FTM
To support DeltaVaultGateway contract on FTM
- Add test file for DeltaVaultGateway with SpookySwap and MiniFairLaunch on FTM
- Fix assertion on old DeltaVaultGateway test file, due to calculation is changed 
[ALPACA-3782](https://100x.atlassian.net/browse/ALPACA-3782)

[main][feat][ALPACA-3782] deltanet gw test with spooky

---

deploy/exec/minifl/config/set-pool-no-timelock.ts
deploy/exec/workers/config/set-beneficial-vault-config-workers03.ts

[main][deploy] xALPACA to Fantom

---

contracts/6/protocol/interest-models/TripleSlopeModel4.sol
contracts/6/protocol/interest-models/TripleSlopeModel5.sol
test/integrations/protocol/TripleSlopeModel.test.ts

[main][feat] Add TripleSlope4 and TripleSlope5

---

package.json

- update npm version to 1.2.30

[main][chore] npm v1.2.30

---

.mainnet.json
.openzeppelin/unknown-56.json
deploy/entities/strats.ts
deploy/exec/delta-neutral-vault/config/init-positions.ts
deploy/exec/strategies/deploy/wswap/share-strategies.ts
deploy/exec/triple-slope-model/deploy/triple-slope-model.ts
deploy/exec/vault-config/config/set-params.ts
deploy/exec/vault/upgrade/vault.ts
deploy/exec/workers/config/set-beneficial-vault-config.ts
deploy/exec/workers/config/set-strategy-ok.ts
deploy/exec/workers/upgrade/workers02.ts
deploy/services/timelock.ts

[main][deploy] Deploy new Market Neutral Vault + Update TripleSlope

---

.fantom_mainnet.json
.openzeppelin/unknown-250.json
deploy/exec/oracles/config/add-primary-source-oracle-medianizer.ts
deploy/exec/workers/deploy/spookyswap-workers03.ts

[main][deploy] BOO-USDC SpookyWorker

---

deploy/deployer/contract-deployer.ts
deploy/deployer/index.ts
deploy/helper/config-file-helper.ts
deploy/helper/index.ts
deploy/interfaces/config.ts
deploy/services/file.ts

This is refactor PR to wrap set of code into class Helper for deploy and update config file.
deployment script has a lot of duplicated code
- contract deployer
- config file helper

[main][feat] contract deployer & config file helper

---

.mainnet.json
.openzeppelin/unknown-56.json
deploy/adaptors/workerlike/biswap-worker/index.ts
deploy/adaptors/workerlike/factory.ts
deploy/entities/worker-like.ts
deploy/exec/oracles/config/add-primary-source-oracle-medianizer.ts
deploy/exec/strategies/deploy/biswap/share-strategies.ts
deploy/exec/strategies/deploy/biswap/vault-strategies.ts
deploy/exec/vault-config/config/set-approved-add-strategies.ts
deploy/exec/vault-config/config/set-params.ts
deploy/exec/workers/deploy/biswap-workers03.ts
deploy/exec/workers/upgrade/workers.ts
package.json
scripts/validate-config.ts
solidity/contracts/6/protocol/interest-models/TripleSlopeModel2.sol
solidity/contracts/6/protocol/workers/single-asset/CakeMaxiWorker02MCV2.sol
test/helpers/swap.ts
test/integrations/protocol/TripleSlopeModel.test.ts
test/integrations/protocol/workers/single-asset/CakeMaxiWorker02MCV2.test.ts

[main][deploy] Deploy Biswap Pools#1

---

solidity/contracts/8.13/nft-staking/NFTStaking.sol

Enhance `NFTStaking` by using a hash of `poolId`, `userAddress` and `nftTokenId` as a unique key to store the user info of staked NFT to save gas and memory usage.
Storing all of the staked token ids could be expensive

[feat/nft-staking] [feat] Use depositId to save gas on NFTStaking

---

deploy/exec/workers/deploy/biswap-workers03.ts
deploy/exec/workers/deploy/cakemaxi-workers02.ts
deploy/exec/workers/deploy/mdex-workers02.ts
deploy/exec/workers/deploy/pancakeswap-v2-workers02.ts
deploy/exec/workers/deploy/spookyswap-workers03.ts
deploy/exec/workers/deploy/tomb-workers03.ts
deploy/exec/workers/deploy/wswap-workers02.ts
deploy/helper/config-file-helper.ts

Refactoring PR for deployment script on workers.
To clean code and automatically update config file after setting and deployed.
- refactor cakemaxi-workers02
- refactor mdex-workers02
- refactor pancakeswap-v2-workers02
- refactor spookyswap-workers03
- refactor tomb-workers03

[main][refactor] workers deployment script

---

solidity/contracts/8.10/protocol/DeltaNeutralVaultGateway.sol
solidity/contracts/8.10/protocol/interfaces/ISwapRouter.sol
solidity/contracts/8.10/protocol/mocks/MockSwapRouter.sol
test/helpers/deploy.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVaultGateway.test.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVaultGatewayNon18Decimals.test.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVaultGatewayWithBiswap.test.ts
test/integrations/protocol/delta-neutral/DeltaNeutralVaultGatewayWithSpookySwap.test.ts

- delta neutral gateway add set router function
- router for reinvest and convert token can be different config

[main][fix] delta neutral gateway add set router function

---

package.json

- publish npm version to be able to retrieve data from AVController, Creditors, and DeltaConfig02 contract

[main][feat]: publish npm version

---

.mainnet.json
.openzeppelin/unknown-56.json
deploy/exec/delta-neutral-vault-config/deploy/delta-neutral-vault-config.ts
deploy/exec/delta-neutral-vault-gateway/deploy/delta-neutral-vault-gateway.ts
deploy/exec/delta-neutral-vault/config/init-positions-v2.ts
deploy/exec/delta-neutral-vault/config/init-positions.ts
deploy/exec/delta-neutral-vault/deploy/delta-neutral-vault.ts
deploy/exec/delta-neutral-worker/deploy/delta-neutral-pcs-worker.ts
deploy/exec/vault-config/config/set-whitelisted-callers.ts

[main][deploy] L3x-BNBBTCB-PCS2

---

package.json
solidity/contracts/8.13/interfaces/ITWAPOracle.sol
solidity/contracts/8.13/interfaces/IxALPACACreditor.sol
solidity/contracts/8.13/xALPACACreditor.sol
solidity/contracts/8.13/xALPACAPriceSetter.sol
solidity/tests/base/BaseTest.sol
solidity/tests/interfaces/xALPACACreditorLike.sol
solidity/tests/interfaces/xALPACAPriceSetterLike.sol
solidity/tests/protocol/private-automated-vault/xALPACACreditor.t.sol
solidity/tests/protocol/private-automated-vault/xALPACAPriceSetter.t.sol

- Add value setter in xALPACACreditor contract
- Automated xALPACA value setter
- `xALPACACreditor.sol`
- `xALPACACreditorLike.sol`
- `xALPACACreditor.t.sol`

[main][feat] xALPACACreditor value setter

---

deploy/exec/av-controller/config/set-param.ts

- using address of vault instead of config

[main][fix]: av controller set incorrect address

---

solidity/contracts/8.13/AutomatedVaultController.sol
solidity/contracts/8.13/DeltaNeutralVault02.sol
solidity/contracts/8.13/xALPACACreditor.sol

Optimize gas for the new DeltaNeutralVault02 for private AV feature
Reduce the gas cost used during operation
- remove default value when allocate new local var in AutomateVaultController
- Reduce contract call in DeltaNeutralVault02

[main][chore] Fix DeltaNeutralVault02 per audit

---

README.md

Update README file
Some information are out-dated
README.md

[main][chore] Update README.md

---

package.json
solidity/contracts/6/protocol/workers/pcs/PancakeswapV2MCV2Worker02.sol
test/integrations/protocol/workers/pcs/Vault_PancakeswapV2MCV2Worker02.test.ts
test/integrations/protocol/workers/pcs/Vault_PancakeswapV2MCV2Worker02_Cake.test.ts

- Pancakev2mcv2worker02 support cake as baseToken
- make reward token to not mixed with supply token

[main][feat] pancakev2mcv2worker02 support cake as basetoken

---

hardhat.config.ts
solidity/contracts/8.10/protocol/DeltaNeutralVault03.sol
solidity/contracts/8.10/protocol/DeltaNeutralVaultConfig03.sol
solidity/contracts/8.10/protocol/interfaces/IDeltaNeutralVaultConfig03.sol
solidity/contracts/8.10/protocol/interfaces/IExecutor.sol

- delta vault to support executor
- DeltaNeutralVault03
- DeltaNeutralVaultConfig03

[main][feat] delta vault to support executor

---

solidity/contracts/6/protocol/interfaces/IBiswapRouter02.sol
solidity/contracts/6/protocol/strategies/biswap/BiswapDnxStrategyAddTwoSidesOptimal.sol
solidity/contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedDnxStrategyAddTwosidesOptimal.sol
test/integrations/protocol/strategies/biswap/Biswap_Dnx_AddTwoSidesOptimal.test.ts
test/integrations/protocol/strategies/pancakeswapv2-restricted/PancakeswapV2_Restricted_Dnx_StrategyAddTwoSidesOptimal.test.ts

- dnx strategy to support swap amount out 0
- swap amount out 0

[main][feat] dnx strategy add two sides optimal

---

deploy/exec/creditor/config/xlalpaca-creditor-setparam.ts
package.json
solidity/contracts/8.13/AutomatedVaultController.sol
solidity/contracts/8.13/DeltaNeutralVault02.sol
solidity/contracts/8.13/xALPACACreditor.sol

- remove empty initializer
- add setValueSetter on xAlpacaCreditors
- block deployment part

[main][hotfix]: remove empty initializer

---

.mainnet.json
.openzeppelin/unknown-56.json
deploy/exec/fairlaunch/config/set-pool.ts
deploy/exec/worker-config/config/set-configs.ts
deploy/exec/workers/deploy/pancakeswap-v2-workers02.ts

[main][deploy] BUSD-CAKE, WBNB-CAKE, and USDT-CAKE pools

---

deploy/exec/av-controller/config/set-param.ts
solidity/contracts/8.13/AutomatedVaultController.sol
solidity/contracts/8.13/DeltaNeutralVault02.sol
solidity/contracts/8.13/interfaces/IController.sol
solidity/tests/interfaces/AutomatedVaultControllerLike.sol
solidity/tests/protocol/private-automated-vault/AutomatedVaultController.t.sol
solidity/tests/protocol/private-automated-vault/DeltaNeutralVault02.t.sol
solidity/tests/protocol/private-automated-vault/FakeAutomateVaultController.sol

Move the business logic check to Controller instead of AV
Reduce gas

[main][feat] Optimize private AV credit logic

---

package.json
solidity/contracts/6/protocol/strategies/spookyswap/SpookySwapDnxStrategyAddTwoSidesOptimal.sol
test/integrations/protocol/strategies/spookyswap/Spookyswap_Dnx_AddTwoSidesOptimal.test.ts

[main][feat] : add dnx spookyswap contract

---

solidity/contracts/8.13/DeltaNeutralVault03.sol
solidity/contracts/8.13/interfaces/IExecutor.sol

- merge private av and executor to DeltaNeutralVault03
- DeltaNeutralVault03.sol

[main][feat] DeltaNeutralVault03 merge private av and executor

---

package.json
solidity/contracts/8.10/protocol/workers/DeltaNeutralPancakeMCV2Worker02.sol
test/helpers/time.ts
test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralPancakeWorker02MCV2.test.ts
test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralPancakeWorker02MCV2_Cake.test.ts

Deltaneutral worker support cake as base token

[main][feat][alpaca 4370] dnx support cake as base token

---

deploy/exec/nft-boosted-leverage-controller/config/set-boosted.ts
deploy/exec/nft-boosted-leverage-controller/deploy/nft-boosted-leverage-controller.ts
deploy/exec/nft-staking/deploy/nft-staking.ts
deploy/helper/config-file-helper.ts
deploy/interfaces/config.ts
package.json
solidity/contracts/8.13/nft-staking/NFTBoostedLeverageController.sol
solidity/contracts/8.13/nft-staking/NFTStaking.sol

Prepare deployment and config setting script for NFTBoostedLeverageController contract
Preparation for contract deployment
- deployment script
- setBoosted script

[main][feat] add nft boosted leverage controller deployment / config script

---

solidity/contracts/6/protocol/ConfigurableInterestVaultConfig.sol
solidity/contracts/6/protocol/workers/WorkerConfig.sol

This PR removed unused `nftStaking` contract state in `ConfigurableVaultConfig` and add an unset check for `nftBoostedLeverageController` constract state in `WorkerConfig`.
Add better contract state validation

[main] [feat] Remove unused NFTStaking contract state

---

deploy/exec/nft-boosted-leverage-controller/config/set-boosted.ts

- enhance set boosted config script
- input workerName instead of address

[main][feat] enhance set boosted config script

---

package.json

[main][chore] update version 1.2.37

---

solidity/contracts/8.13/DirectionalVault.sol
solidity/tests/protocol/directional-vault/DirectionalVault.t.sol

Rename stuff with `DeltaNeutral` to `Directional` in `DirectionalVault.sol`

[main] [chore] rename DeltaNeutral to Directional

---

solidity/contracts/8.15/AIP8AUSDStaking.sol
solidity/tests/protocol/aip-8/AIP8AUSDStaking_TestLock.t.sol

resolve bug on AIP8 AUSD staking
- In case that user can increase lp locking amount with the same unlock date

[main][fix] resolve bug on AIP8 AUSD staking

---

.mainnet.json
deploy/exec/delta-neutral-vault-config/config/set-executor.ts
deploy/exec/delta-neutral-vault-config/config/set-strategies.ts
deploy/exec/delta-neutral-vault-config/config/set-swap-fee.ts
deploy/exec/delta-neutral-vault-config/deploy/delta-neutral-vault-config02.ts
deploy/exec/delta-neutral-vault-gateway/deploy/delta-neutral-vault-gateway.ts
deploy/exec/delta-neutral-worker/deploy/delta-neutral-pcs-worker.ts
deploy/exec/directional-vault/config/init-positions.ts
deploy/exec/directional-vault/deploy/directional-vault.ts
deploy/exec/vault-config/config/set-whitelisted-callers.ts
deploy/helper/config-file-helper.ts
deploy/interfaces/config.ts
package.json

- directional vault deployment script

[main][feat] directional vault deploy script

---

solidity/contracts/8.15/AIP8AUSDStaking.sol
solidity/contracts/8.15/interfaces/IFairLaunch.sol
solidity/tests/interfaces/AIP8AUSDStakingLike.sol
solidity/tests/protocol/aip-8/AIP8AUSDStakingBase.sol
solidity/tests/protocol/aip-8/AIP8AUSDStaking_TestEmergencyWithdraw.t.sol
solidity/tests/protocol/aip-8/AIP8AUSDStaking_TestHarvest.t.sol
solidity/tests/protocol/aip-8/AIP8AUSDStaking_TestLock.t.sol
solidity/tests/protocol/aip-8/AIP8AUSDStaking_TestUnlock.t.sol

- add emergencyWithdraw function to AIP8
-  add unit tests
- users should be able to withdraw fund without caring about rewards

[main][feat] AIP8 emergencyWithdraw

---

.mainnet.json
.openzeppelin/unknown-56.json
deploy/exec/av-controller/config/set-params.ts
deploy/exec/workers/config/set-reinvestor-ok.ts
package.json

[main][deploy] AIP8 AUSD Staking

---

.fantom_mainnet.json
package.json
solidity/contracts/8.10/protocol/apis/spooky/Address.sol
solidity/contracts/8.10/protocol/apis/spooky/Context.sol
solidity/contracts/8.10/protocol/apis/spooky/Ownable.sol
solidity/contracts/8.10/protocol/apis/spooky/SafeERC20.sol
solidity/contracts/8.10/protocol/apis/spooky/SpookyMasterChefV2.sol
solidity/contracts/8.10/protocol/interfaces/ISpookyMasterChefV2.sol
solidity/contracts/8.10/protocol/interfaces/ISpookyRewarder.sol

Add SpookyMasterchefV2 contract and its dependencies.
Spooky team are upgrading their MasterChef.
- just added the contracts

[main][feat] SpookyMasterchefV2

---

solidity/contracts/8.13/DeltaNeutralVault04.sol
solidity/tests/interfaces/DeltaNeutralVault04Like.sol
solidity/tests/protocol/delta-neutral-04/DeltaNeutralVault04_Repurchase.t.sol

Change from discount rate upon repurchase to bonus amount out
To fix having to transfer back discount in case of native token
- DeltaNeutralVault04
- Test case

[feat][feat] Switch from discount to bonus

---

solidity/contracts/8.13/DeltaNeutralVault04.sol
solidity/contracts/8.13/DeltaNeutralVaultConfig02.sol
solidity/contracts/8.13/interfaces/IDeltaNeutralVaultConfig02.sol
solidity/tests/fake/FakeDeltaNeutralVaultConfig02.sol
solidity/tests/interfaces/DeltaNeutralVault04Like.sol
solidity/tests/protocol/delta-neutral-04/DeltaNeutralVault04Base.t.sol
solidity/tests/protocol/delta-neutral-04/DeltaNeutralVault04_Repurchase.t.sol

Fix per audit suggestion
Optimize code
- transferring token in
- fix substract underflow

[feat][feat] Fix per audit

---

.mainnet.json
.openzeppelin/unknown-56.json
deploy/exec/workers/deploy/pancakeswap-v2-workers02.ts

[main][deploy] pSTAKE-BUSD and stkBNB-WBNB pool

---

foundry.toml

Update foundry.toml
new version of foundry block read/write operation if not set
- foundry.toml

[main][chore] Add file permission in foundry.toml

---

solidity/contracts/8.10/protocol/workers/biswap/DeltaNeutralBiswapWorker03.sol
solidity/contracts/8.10/protocol/workers/pancakeswap/DeltaNeutralPancakeMCV2Worker02.sol

Delta worker health will return some big number to bypass work factor check at vault
To allow new executor to perform without hitting work factor check

[main][feat] Bypass work factor for AV

---

deploy/exec/workers/upgrade/workers.ts

- add get dnx biswap worker factory in worker upgrade script

[main][feat] worker upgrade script

---

deploy/exec/strategies/config/set-whitelisted-workers.ts
package.json

- refactor setWorkersOk script
- improve readability

[main][feat] refactor setWorkersOk script

---

.mainnet.json
deploy/exec/triple-slope-model/deploy/triple-slope-model.ts
deploy/exec/vault-config/config/set-params.ts
solidity/contracts/6/protocol/interest-models/TripleSlopeModel10.sol
solidity/contracts/6/protocol/interest-models/TripleSlopeModel8.sol
solidity/contracts/6/protocol/interest-models/TripleSlopeModel9.sol
solidity/tests/protocol/interest-model/TripleSlope10.t.sol
solidity/tests/protocol/interest-model/TripleSlope8.t.sol
solidity/tests/protocol/interest-model/TripleSlope9.t.sol

[main][deploy] Adjust triple slope according to AIP-10

---

deploy/exec/delta-neutral-health-checker/deploy/delta-neutral-health-checker.ts
solidity/contracts/8.13/DeltaNeutralVault04.sol
solidity/tests/protocol/delta-neutral-04/DeltaNeutralVault04_Deposit.t.sol

Share price was off if one of the position has debt ratio more than 100%
Fix wrong deposit share calculation

[main][fix] Support negative equity value

---

deploy/exec/delta-neutral-vault-config/config/set-whitelisted-callers.ts
deploy/exec/delta-neutral-vault-config/config/set-whitelisted-repurchasers.ts
deploy/exec/fairlaunch/config/set-alpaca-per-block.ts
deploy/exec/ownable/config/transfer-ownership.ts
deploy/exec/vault-config/config/set-whitelisted-callers.ts
package.json

[main][deploy] Whitelist & emission adjust

---

package.json
solidity/contracts/8.13/AVMigration.sol
solidity/tests/protocol/av-migration/AVMigration.t.sol

- allow user to partially migrate share

[main][feat] AVMigration partial migrate share

---

.mainnet.json
deploy/exec/delta-neutral-vault-config/config/set-whitelisted-callers.ts

[main][delpoy] AV Migration

---

deploy/exec/ausd/upgrade/aip8-ausd-staking.ts
package.json
solidity/contracts/8.15/AIP8AUSDStaking.sol
solidity/tests/protocol/aip-8/AIP8AUSDStaking_TestUnlock.t.sol

- we want user to unlock and also get alpaca reward

[main][feat] aip8 no longer check lock until

---

.openzeppelin/unknown-56.json
deploy/exec/ausd/upgrade/aip8-ausd-staking.ts
deploy/exec/av-controller/upgrade/av-controller.ts
deploy/exec/revenue-treasury/upgrade/revenue-treasury.ts
deploy/interfaces/config.ts
package.json
solidity/contracts/8.10/protocol/RevenueTreasury.sol
test/integrations/protocol/RevenueTreasury.test.ts

[main][deploy] Disabled xALPACA credit

---

.openzeppelin/unknown-56.json
deploy/exec/strategies/deploy/pancakeswap-v2/share-strategies.ts
deploy/exec/vault/upgrade/vault.ts
deploy/exec/workers/config/set-strategy-ok.ts
deploy/exec/workers/upgrade/workers.ts
solidity/contracts/6/protocol/workers/pcs/PancakeswapV2MCV2WorkerDisabledLiquidation.sol

[main][feat] Force close stkBNB-WBNB positions

---

.mainnet.json
deploy/exec/delta-neutral-vault-reader/deploy/delta-neutral-vault-reader.ts
deploy/helper/config-file-helper.ts
deploy/interfaces/config.ts

[main][chore] remove reader config from .mainnet

---

.openzeppelin/unknown-250.json
.openzeppelin/unknown-56.json
deploy/exec/revenue-treasury/upgrade/revenue-treasury.ts
solidity/contracts/8.10/protocol/FantomRevenueTreasury.sol

[main][deploy] Upgrade revenue treasury on Fantom

---

solidity/contracts/8.15/AIP15.sol
solidity/contracts/8.15/interfaces/IProxyToken.sol

[main][feat] AIP-15: Handling Sources of Incentives for Alperp and AF2.0

---

deploy/exec/worker-reader/deploy/worker-reader.ts
package.json
solidity/contracts/8.10/protocol/WorkerReader.sol
solidity/contracts/8.10/protocol/interfaces/IGenericMasterChef.sol
solidity/contracts/8.10/protocol/interfaces/IWorker.sol
solidity/contracts/8.10/protocol/interfaces/IWorkerReader.sol

- a reader contract for workers

[main][feat] worker reader contract

---

deploy/exec/delta-neutral-vault-config/deploy/delta-neutral-vault-config02.ts

- add setSwapFee config to dnxConfig02 deployment script

[main][chore] update dnxConfig02 deployment script

---

.mainnet.json
.openzeppelin/bsc.json
deploy/exec/delta-neutral-vault-config/config/set-strategies.ts
deploy/exec/delta-neutral-vault-config/config/set-vault-limit.ts
deploy/exec/delta-neutral-vault-config/deploy/delta-neutral-vault-config02.ts
deploy/exec/delta-neutral-vault-gateway/deploy/delta-neutral-vault-gateway.ts
deploy/exec/delta-neutral-vault/config/init-positions-vault04.ts
deploy/exec/delta-neutral-vault/deploy/delta-neutral-vault04.ts
deploy/exec/delta-neutral-worker/deploy/delta-neutral-pcs-worker.ts
deploy/exec/oracles/config/add-price-source-chainlink2.ts
deploy/exec/oracles/config/add-primary-source-oracle-medianizer.ts
deploy/exec/triple-slope-model/deploy/triple-slope-model.ts
deploy/exec/vault-config/config/set-params.ts
deploy/exec/vault-config/config/set-whitelisted-callers.ts
deploy/helper/config-file-helper.ts
solidity/contracts/6/protocol/interest-models/TripleSlopeModel11.sol
solidity/contracts/6/protocol/interest-models/TripleSlopeModel12.sol
solidity/contracts/6/protocol/interest-models/TripleSlopeModel13.sol
solidity/contracts/6/protocol/interest-models/TripleSlopeModel14.sol
solidity/contracts/6/protocol/interest-models/TripleSlopeModel15.sol
solidity/tests/protocol/interest-model/TripleSlope11.t.sol
solidity/tests/protocol/interest-model/TripleSlope12.t.sol
solidity/tests/protocol/interest-model/TripleSlope13.t.sol
solidity/tests/protocol/interest-model/TripleSlope14.t.sol
solidity/tests/protocol/interest-model/TripleSlope15.t.sol

[main][deploy] Update Triple Slopes

---

solidity/contracts/8.11/utils/MultiCall3.sol

[main][chore] Add MultiCall3 implementation.

---

deploy/exec/delta-neutral-vault-config/config/set-whitelisted-repurchasers.ts
deploy/exec/delta-neutral-vault-config/deploy/delta-neutral-vault-config02.ts
solidity/contracts/8.13/DeltaNeutralVault04.sol
solidity/contracts/8.13/DeltaNeutralVaultConfig02.sol

[main][fix] Unnecessary multiplication

---

.fantom_mainnet.json
.openzeppelin/unknown-250.json
deploy/exec/delta-neutral-vault-config/upgrade/delta-neutral-vault-config.ts
deploy/exec/delta-neutral-vault/upgrade/delta-neutral-vault.ts
deploy/exec/strategies/config/set-whitelisted-delta-neutral-vault-timelock.ts
deploy/exec/workers/upgrade/workers.ts
deploy/services/timelock.ts

[main][deploy] Terminate AVs on fantom

---

deploy/exec/delta-neutral-vault-config/config/adjust-leverage.ts
package.json

[main][feat] adjust leverage script

---

.mainnet.json

[main][chore] update mainnet

---

deploy/exec/vault/config/aip25-migrate.ts
deploy/exec/workers/upgrade/workers.ts
package.json
solidity/contracts/6/protocol/MigratedVault.sol
solidity/contracts/6/protocol/VaultAip25.sol
solidity/contracts/6/protocol/interfaces/IMoneyMarket.sol
solidity/contracts/6/protocol/interfaces/IMoneyMarketAccountManager.sol
solidity/contracts/6/protocol/workers/Biswap/BiswapWorker03DisabledLiquidation.sol
solidity/contracts/6/protocol/workers/single-asset/CakeMaxiWorker02MCV2DisabledLiquidation.sol
solidity/tests/forks/aip-25/VaultAIP25_BaseTest.t.sol
solidity/tests/forks/aip-25/VaultAIP25_ClaimForTest.t.sol
solidity/tests/forks/aip-25/VaultAIP25_MigrateTest.t.sol
solidity/tests/forks/aip-25/VaultAIP25_WithdrawTest.t.sol

[main][feat] vault migration

---

deploy/exec/revenue-treasury/config/set-revenue-distributor.ts
deploy/exec/revenue-treasury/config/set-reward-time.ts
package.json
solidity/contracts/8.10/protocol/RevenueTreasury.sol
solidity/contracts/8.10/protocol/interfaces/IxALPACAv2RevenueDistributor.sol
solidity/tests/forks/revenue-treasury/RevenueTreasury_BaseTest.t.sol
solidity/tests/forks/revenue-treasury/RevenueTreasury_FeedGrasshouseTest.t.sol

[main][feat] upgrade revenue treasury to feed revenue distributor

---

.openzeppelin/bsc.json
deploy/exec/revenue-treasury/config/set-revenue-distributor.ts
deploy/exec/revenue-treasury/upgrade/revenue-treasury.ts
deploy/services/multisig/gnosis-safe/index.ts
deploy/services/multisig/interface.ts
deploy/services/timelock.ts

[main][deploy] New revenue treasury

---

.openzeppelin/bsc.json
deploy/exec/vault/upgrade/vault.ts
deploy/exec/worker-config/config/emerge-set-accept-debt.ts
deploy/exec/worker-config/config/set-configs.ts
deploy/exec/workers/config/set-strategy-ok.ts
deploy/exec/workers/upgrade/workers.ts
package.json
yarn.lock

[main][deploy] Deprecate batch 3

---

deploy/exec/workers/config/set-reward-path.ts

[main][fix] write file outside loop

---

.openzeppelin/bsc.json
deploy/exec/vault/upgrade/vault.ts
solidity/contracts/6/protocol/VaultAip25.sol
solidity/contracts/6/protocol/interfaces/IMoneyMarket.sol
solidity/contracts/6/protocol/interfaces/IMoneyMarketAccountManager.sol
solidity/tests/forks/aip-25/VaultAIP25_WithdrawTest.t.sol

[main][feat] allow withdrawal after migration

---

deploy/exec/vault/config/aip29-hotfix-set-debt-val.ts.ts
package.json
solidity/contracts/6/protocol/VaultAip29HotFix.sol
solidity/tests/forks/aip-29/VaultAIP29_Hotfix.t.sol

[main][hotfix] Allow withdrawal for SCIX
